export const MEMBERS = [
  {
    id: 69,
    fullName: "Nico Zubia",
    firstName: "Nico",
    lastName: "Zubia",
    email: "nico.zubia@example.com",
    memberType: "dependent",
    membership: "Test Household",
    salesforceId: "001XX000004DGbQ",
    initials: "NZ",
    householdId: "HH-1042",
    allergens: "Peanuts, shellfish",
    bloodType: "O+",
    phone: "+1 (555) 010-0069",
    birthDate: "1992-03-14",
    status: "Active",
    extraServicesBalance: "4 sessions",
    contraindications: "None documented",
  },
  {
    id: 67,
    fullName: "Dasecond Doe",
    firstName: "Dasecond",
    lastName: "Doe",
    email: "dasecond.doe@example.com",
    memberType: "secondary",
    membership: "Test Household",
    salesforceId: "001XX000004DGbR",
    initials: "DD",
    householdId: "HH-1042",
    allergens: "—",
    bloodType: "A+",
    phone: "+1 (555) 010-0067",
    birthDate: "1988-11-02",
    status: "Active",
    extraServicesBalance: "2 sessions",
    contraindications: "Avoid high-intensity load on left shoulder",
  },
  {
    id: 34,
    fullName: "Owen Member",
    firstName: "Owen",
    lastName: "Member",
    email: "owen@launchpadlab.com",
    memberType: "primary",
    membership: "—",
    salesforceId: "001XX000004DGbS",
    initials: "OM",
    householdId: "HH-1001",
    allergens: "—",
    bloodType: "B+",
    phone: "+1 (555) 010-0034",
    birthDate: "1990-07-21",
    status: "Active",
    extraServicesBalance: "8 sessions",
    contraindications: "—",
  },
  {
    id: 1,
    fullName: "Test Member",
    firstName: "Test",
    lastName: "Member",
    email: "test.member@example.com",
    memberType: "primary",
    membership: "Test Household",
    salesforceId: "001XX000004DGbT",
    initials: "TM",
    householdId: "HH-1000",
    allergens: "Latex",
    bloodType: "AB-",
    phone: "+1 (555) 010-0001",
    birthDate: "1985-01-15",
    status: "Active",
    extraServicesBalance: "0 sessions",
    contraindications: "Oral contrast dyes",
  },
];

export function getMemberById(rawId) {
  const id = Number(rawId);
  if (Number.isNaN(id)) return undefined;
  return MEMBERS.find((m) => m.id === id);
}
