/** Seed rows for the protocols table (POC). User-saved protocols are prepended from localStorage. */
export const BASE_PROTOCOLS = [
  { id: "PR-001", name: "Foundational metabolic support", version: "2.1", updated: "Apr 26, 2026", status: "Active" },
  { id: "PR-002", name: "Training block — strength", version: "1.0", updated: "Apr 20, 2026", status: "Draft" },
  { id: "PR-003", name: "Recovery & regeneration", version: "3.4", updated: "Apr 12, 2026", status: "Active" },
  { id: "PR-004", name: "Diagnostics prep", version: "1.2", updated: "Mar 28, 2026", status: "Archived" },
  { id: "PR-005", name: "Sleep & circadian reset", version: "1.4", updated: "Mar 22, 2026", status: "Active" },
  { id: "PR-006", name: "Gut restoration — post antibiotics", version: "2.0", updated: "Mar 18, 2026", status: "Draft" },
  {
    id: "PR-007",
    name: "Parasite Cleanse Protocol",
    version: "1.0",
    updated: "May 8, 2026",
    status: "Active",
  },
  { id: "PR-008", name: "Thyroid optimization — subclinical", version: "1.1", updated: "May 2, 2026", status: "Active" },
  { id: "PR-009", name: "Detoxification support (Phase I–II)", version: "2.2", updated: "Apr 30, 2026", status: "Draft" },
  { id: "PR-010", name: "Athlete — competition taper", version: "1.0", updated: "Apr 28, 2026", status: "Active" },
  { id: "PR-011", name: "Women’s hormone balance", version: "3.0", updated: "Apr 25, 2026", status: "Active" },
  { id: "PR-012", name: "Cardiometabolic risk reduction", version: "1.3", updated: "Apr 22, 2026", status: "Archived" },
  { id: "PR-013", name: "Longevity — NAD+ stack", version: "0.9", updated: "Apr 19, 2026", status: "Draft" },
  { id: "PR-014", name: "Mold exposure — binders", version: "1.5", updated: "Apr 16, 2026", status: "Active" },
  { id: "PR-015", name: "Pediatric — eczema protocol", version: "1.0", updated: "Apr 14, 2026", status: "Draft" },
  { id: "PR-016", name: "Preconception — 90-day", version: "2.4", updated: "Apr 10, 2026", status: "Active" },
  { id: "PR-017", name: "Postpartum recovery", version: "1.2", updated: "Apr 6, 2026", status: "Active" },
  { id: "PR-018", name: "Cognitive clarity — focus stack", version: "1.0", updated: "Apr 3, 2026", status: "Draft" },
  { id: "PR-019", name: "Travel — immune support", version: "1.1", updated: "Mar 30, 2026", status: "Active" },
  { id: "PR-020", name: "Seasonal allergy mitigation", version: "1.0", updated: "Mar 25, 2026", status: "Archived" },
];
