/** Program row for list + edit lookup */
export const PROGRAMS_MOCK = [
  { id: "S1", programName: "Anti-inflammatory stack", pillarKey: "supplements", numberOfItems: 3 },
  { id: "S2", programName: "Core micronutrients", pillarKey: "supplements", numberOfItems: 5 },
  { id: "N1", programName: "Vegan", pillarKey: "nutrition", numberOfItems: 6 },
  { id: "N2", programName: "Vegetarian", pillarKey: "nutrition", numberOfItems: 4 },
  { id: "T1", programName: "Muscle Build 4-Day Microcycle", pillarKey: "training", numberOfItems: 8 },
  { id: "R1", programName: "Recovery Intensive Week", pillarKey: "recovery", numberOfItems: 7 },
  { id: "D1", programName: "Diagnostic Baseline", pillarKey: "diagnostics", numberOfItems: 12 },
  { id: "G1", programName: "Regeneration block A", pillarKey: "regeneration", numberOfItems: 5 },
  { id: "S3", programName: "Drainage support", pillarKey: "supplements", numberOfItems: 4 },
  { id: "N3", programName: "Low-FODMAP", pillarKey: "nutrition", numberOfItems: 9 },
  { id: "T2", programName: "Hypertrophy upper focus", pillarKey: "training", numberOfItems: 10 },
  { id: "R2", programName: "Sleep & stress stack", pillarKey: "recovery", numberOfItems: 3 },
  { id: "D2", programName: "Metabolic panel prep", pillarKey: "diagnostics", numberOfItems: 6 },
  { id: "G2", programName: "Blue light protocol", pillarKey: "regeneration", numberOfItems: 4 },
  { id: "S4", programName: "Binder rotation", pillarKey: "supplements", numberOfItems: 2 },
  { id: "N4", programName: "Keto-adjacent", pillarKey: "nutrition", numberOfItems: 11 },
  { id: "T3", programName: "Endurance base", pillarKey: "training", numberOfItems: 14 },
  { id: "R3", programName: "Post-travel reset", pillarKey: "recovery", numberOfItems: 5 },
  { id: "D3", programName: "GI mapping week", pillarKey: "diagnostics", numberOfItems: 8 },
  { id: "G3", programName: "Circadian anchor", pillarKey: "regeneration", numberOfItems: 6 },
  { id: "S5", programName: "Mineral repletion", pillarKey: "supplements", numberOfItems: 7 },
  { id: "N5", programName: "Mediterranean", pillarKey: "nutrition", numberOfItems: 5 },
  { id: "T4", programName: "Mobility micro-dose", pillarKey: "training", numberOfItems: 4 },
  { id: "R4", programName: "Sauna contrast", pillarKey: "recovery", numberOfItems: 3 },
  { id: "D4", programName: "Cardio screening", pillarKey: "diagnostics", numberOfItems: 9 },
  { id: "G4", programName: "Red-light evening", pillarKey: "regeneration", numberOfItems: 2 },
  { id: "S6", programName: "Antimicrobial pulse", pillarKey: "supplements", numberOfItems: 6 },
  { id: "N6", programName: "High protein cut", pillarKey: "nutrition", numberOfItems: 10 },
  { id: "T5", programName: "PPL 6-day block", pillarKey: "training", numberOfItems: 12 },
  { id: "R5", programName: "Soft tissue care", pillarKey: "recovery", numberOfItems: 4 },
  { id: "D5", programName: "Inflammation markers", pillarKey: "diagnostics", numberOfItems: 7 },
  { id: "G5", programName: "Morning sunlight", pillarKey: "regeneration", numberOfItems: 3 },
  { id: "S7", programName: "Liver support", pillarKey: "supplements", numberOfItems: 5 },
  { id: "N7", programName: "Anti-candida diet", pillarKey: "nutrition", numberOfItems: 8 },
  { id: "T6", programName: "Strength mesocycle", pillarKey: "training", numberOfItems: 9 },
  { id: "R6", programName: "Nervous system downshift", pillarKey: "recovery", numberOfItems: 6 },
  { id: "D6", programName: "Thyroid follow-up", pillarKey: "diagnostics", numberOfItems: 5 },
  { id: "G6", programName: "Cold exposure intro", pillarKey: "regeneration", numberOfItems: 4 },
  { id: "S8", programName: "Electrolyte balance", pillarKey: "supplements", numberOfItems: 3 },
  { id: "N8", programName: "Intermittent fasting", pillarKey: "nutrition", numberOfItems: 7 },
  { id: "T7", programName: "ACL return-to-run", pillarKey: "training", numberOfItems: 11 },
];

export function getProgramById(id) {
  return PROGRAMS_MOCK.find((p) => p.id === id) ?? null;
}
