/** Care team (Amy) dashboard — mostly approved queue; first row opens care-review protocol builder. */
export const NEEDS_ATTENTION_AMY = [
  {
    id: "amy-na-1",
    date: "May 1, 2026",
    member: "Casey Brown",
    task: "Approve supplement stack",
    description: "New items pending care team sign-off before member activation.",
    status: "Awaiting Approval",
    protocolBuilderHref: "/protocol-builder?variant=care-review",
  },
  {
    id: "amy-na-2",
    date: "Apr 30, 2026",
    member: "Jordan Lee",
    task: "Review training block",
    description: "Consent on file; protocol finalized and released to member.",
    status: "Approved",
  },
  {
    id: "amy-na-3",
    date: "Apr 29, 2026",
    member: "Riley Chen",
    task: "Diagnostics prep packet",
    description: "GI-MAP instructions sent; member acknowledged.",
    status: "Approved",
  },
  {
    id: "amy-na-4",
    date: "Apr 28, 2026",
    member: "Sam Rivera",
    task: "Nutrition plan sign-off",
    description: "Macros and meal templates approved.",
    status: "Approved",
  },
  {
    id: "amy-na-5",
    date: "Apr 27, 2026",
    member: "Taylor Brooks",
    task: "Recovery services bundle",
    description: "Massage and sauna cadence confirmed.",
    status: "Approved",
  },
  {
    id: "amy-na-6",
    date: "Apr 26, 2026",
    member: "Morgan Ellis",
    task: "Supplement renewal",
    description: "Autoship stack reviewed; no changes.",
    status: "Approved",
  },
  {
    id: "amy-na-7",
    date: "Apr 25, 2026",
    member: "Jamie Park",
    task: "Lab requisition",
    description: "DEXA and blood panel approved.",
    status: "Approved",
  },
  {
    id: "amy-na-8",
    date: "Apr 24, 2026",
    member: "Alex Kim",
    task: "Protocol amendment",
    description: "Evening magnesium timing update approved.",
    status: "Approved",
  },
  {
    id: "amy-na-9",
    date: "Apr 23, 2026",
    member: "Chris Johnson",
    task: "Onboarding checklist",
    description: "All intake tasks completed and verified.",
    status: "Approved",
  },
  {
    id: "amy-na-10",
    date: "Apr 22, 2026",
    member: "Pat Ng",
    task: "Care plan summary",
    description: "Quarterly summary published to member app.",
    status: "Approved",
  },
];
